### ISSUE TITLE
trying to compile on Openindiana

### ISSUE THREAD

**Issue by geoffgnaa** [matusso/zfs-zabbix#1]
I am trying to compile this on OI and I am getting an error on 

gmake 
/opt/gcc/4.4.4/bin/gcc -Wall -Wextra -std=c99 -pedantic -lzfs -lnvpair    -c -o config.o config.c
/opt/gcc/4.4.4/bin/gcc -Wall -Wextra -std=c99 -pedantic -lzfs -lnvpair    -c -o fsutil.o fsutil.c
fsutil.c: In function ‘zpool_get_dedupratio’:
fsutil.c:65: error: too many arguments to function ‘zpool_get_prop’
fsutil.c: In function ‘zpool_get_health’:
fsutil.c:75: error: too many arguments to function ‘zpool_get_prop’
fsutil.c: In function ‘zpool_get_poolname’:
fsutil.c:84: error: too many arguments to function ‘zpool_get_prop’
gmake: *** [fsutil.o] Error 1

any ideas?

thanks,

Geoff

**Comment by matusso** [comment]
problem is probably in different version of zfs. I have the same problem with compile on "zfsonlinux". I will fix this bug, but it takes the time.

**Comment by geoffgnaa** [comment]
OK, if you have something you want me to test, please let me know.

thanks!!
