### ISSUE TITLE
Zabbix-agent config

### ISSUE THREAD

**Issue by Compizfox** [matusso/zfs-zabbix#2]
Hi,

I'd like to use this to monitor my ZFS using Zabbix, but I believe your code is missing a config for the zabbix-agent. I successfully compiled the *zio* program, but I don't know how to 'tie together' the script (*zfs-zabbix.sh*) and zabbix-agent.

Could you tell me how to do that?

**Comment by matusso** [comment]
Hi,

I added zabbix_agentd.conf to repository (templates dir), in this config is using configuration parameter "UserParameter" for define (zfs-zabbix.sh) own script. You need to import zabbix template (zbx_export_templates.xml) from "templates" dir and define zabbix value mapping. You can find it in README.md in "templates" dir. If you still have problem, contact me.

**Comment by Compizfox** [comment]
Thanks!

I installed the template and configured the zabbix-agent, but for some reasons I don't have any items or graphs for the host I assigned the template to.

I think something is wrong with the discovery. I see that the discovery is installed, but it hasn't discovered any pools/disks. The error I get is `Value should be a JSON object.`.

**Comment by matusso** [comment]
hello, I added new version of zfs_zabbix.sh script, you can pull and try it now. If problem still exists, please write me your operating system.

**Comment by Compizfox** [comment]
Unfortunately it still doesn't work.

If it is of any help, the output of *zfs_zabbix.sh* is the following: 

	# ./zfs_zabbix.sh
	status: Some supported features are not enabled on the pool. The pool can
			still be used, but some features are unavailable.
	action: Enable all features using 'zpool upgrade'. Once this is done,
			the pool may no longer be accessible by software that does not support
			the features. See zpool-features(5) for details.
	{
			"data":[

					{ "{#FSNAME}":"Data",           "{#FSTYPE}":"zfs" },
					{ "{#FSNAME}":"Data2",          "{#FSTYPE}":"zfs" },
					{ "{#FSNAME}":"zroot",          "{#FSTYPE}":"zfs" }

			]
	}

Could it be that the warning message at the beginning shouldn't be there?

I'm using FreeBSD 10.2.

**Comment by matusso** [comment]
Of course, I hope, the last commit solved the problem. Can you test it now?
thanks.

**Comment by Compizfox** [comment]
Thanks, but the result is the same. Apparantly the "status" message is not outputted to stderr but to stdout.

**Comment by matusso** [comment]
hello, I test this version on my enviroment and it works, when I send stderr to /dev/null, the status message isn't showing.

root@omnios-test:/root/zio# ./zio -s pools -f json 
status: One or more devices could not be opened.  Sufficient replicas exist for
        the pool to continue functioning in a degraded state.
   see: http://zfsonlinux.org/msg/ZFS-8000-2Q
{
        "data":[

                { "{#FSNAME}":"data",           "{#FSTYPE}":"zfs" },
                { "{#FSNAME}":"rpool",          "{#FSTYPE}":"zfs" }

        ]
}
root@omnios-test:/root/zio# ./zio -s pools -f json 2>/dev/null
{
        "data":[

                { "{#FSNAME}":"data",           "{#FSTYPE}":"zfs" },
                { "{#FSNAME}":"rpool",          "{#FSTYPE}":"zfs" }

        ]
}

**Comment by matusso** [comment]
I rewrite 'zpool_print_vdev' function, that it writes status logs to file, but it takes time.

**Comment by Compizfox** [comment]
Hi,

This is not the case on my system.

    lars@ILOS:~$ zio -s pools -f json
    status: Some supported features are not enabled on the pool. The pool can
            still be used, but some features are unavailable.
    action: Enable all features using 'zpool upgrade'. Once this is done,
            the pool may no longer be accessible by software that does not support
            the features. See zpool-features(5) for details.
    {
            "data":[

                    { "{#FSNAME}":"Data",           "{#FSTYPE}":"zfs" },
                    { "{#FSNAME}":"Data2",          "{#FSTYPE}":"zfs" },
                    { "{#FSNAME}":"zroot",          "{#FSTYPE}":"zfs" }

            ]
    }
    lars@ILOS:~$ zio -s pools -f json 2>/dev/null
    status: Some supported features are not enabled on the pool. The pool can
            still be used, but some features are unavailable.
    action: Enable all features using 'zpool upgrade'. Once this is done,
            the pool may no longer be accessible by software that does not support
            the features. See zpool-features(5) for details.
    {
            "data":[

                    { "{#FSNAME}":"Data",           "{#FSTYPE}":"zfs" },
                    { "{#FSNAME}":"Data2",          "{#FSTYPE}":"zfs" },
                    { "{#FSNAME}":"zroot",          "{#FSTYPE}":"zfs" }

            ]
    }

Maybe this is some FreeBSD-specific thing?

**Comment by matusso** [comment]
What shell do you use? you have to use bash, because I have the same problem in 'csh' for example.
Install bash via: pkg install bash

**Comment by Compizfox** [comment]
I do use bash. In fact, it's in *zfs_zabbix.sh* (`#!/usr/bin/env bash`)

**Comment by matusso** [comment]
and do you have mounted filedescriptors for stdout/stderr?
~# mount -t fdescfs fdesc /dev/fd

**Comment by matusso** [comment]
now, it's fixed in source code. Can you test it now?
