### ISSUE TITLE
Compilation fails: Ubuntu 16.04 LTS, ZFS 0.6.5.6

### ISSUE THREAD

**Issue by alxdlv** [matusso/zfs-zabbix#8]
Log: http://pastebin.com/7xg4YfxT

**Comment by matusso** [comment]
I tried to compile from new project [zabbix-modules](https://github.com/matusso/zabbix-modules) and it is possible to build and run under Ubuntu 16.04. You try it from new project please and if doesn't work, create an issue under new project.
